# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2020 Amazon.com Inc

ifdef CONFIG_EINK
obj-$(CONFIG_CMD_HWID) += hwid.o
obj-$(CONFIG_CMD_BOOTEINK) += booteink.o
obj-$(CONFIG_CMD_PROVISION) += provision.o
obj-$(CONFIG_CMD_UTEST) += cmd_utest.o
endif # CONFIG_EINK
