/*****************************************************************************
 * Copyright (C) 2016 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * Accelerometer Sensor Driver
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 *
 *****************************************************************************/

#ifndef __HWTCON_REG_H__
#define __HWTCON_REG_H__

#include "hwtcon_driver.h"

/*
 * mmsys		0x14000000
 * img rdma	0x14008000
 * wb rdma	0x14009000
 * wb wdma	0x1400A000
 * pipeline	0x1400B000
 * regal		0x1400C000
 * paper_top	0x1400D000
 */

/* MMSYS: 0x14000000*/
#define MMSYS_CG_CON0	(hwtcon_driver_get_mmsys_va() + 0x100)

/* IMG_RDMA: 0x14008000 */
#define PP_IMG_RDMA_INT_ENABLE_VA (hwtcon_driver_get_img_rdma_va() + 0x000)
#define PP_IMG_RDMA_INT_STATUS_VA (hwtcon_driver_get_img_rdma_va() + 0x004)
#define PP_IMG_RDMA_GLOBAL_CON_VA (hwtcon_driver_get_img_rdma_va() + 0x010)
#define PP_IMG_RDMA_SIZE_CON_0_VA (hwtcon_driver_get_img_rdma_va() + 0x014)
#define PP_IMG_RDMA_SIZE_CON_1_VA (hwtcon_driver_get_img_rdma_va() + 0x018)
#define PP_IMG_RDMA_TARGET_LINE_VA (hwtcon_driver_get_img_rdma_va() + 0x01c)
#define PP_IMG_RDMA_MEM_CON_VA (hwtcon_driver_get_img_rdma_va() + 0x024)
#define PP_IMG_RDMA_MEM_SRC_PITCH_VA (hwtcon_driver_get_img_rdma_va() + 0x02C)
#define PP_IMG_RDMA_MEM_GMC_SETTING_0_VA (hwtcon_driver_get_img_rdma_va() + \
	0x030)
#define PP_IMG_RDMA_MEM_SLOW_CON_VA (hwtcon_driver_get_img_rdma_va() + 0x034)
#define PP_IMG_RDMA_MEM_GMC_SETTING_1_VA (hwtcon_driver_get_img_rdma_va() + \
	0x038)
#define PP_IMG_RDMA_FIFO_CON_VA (hwtcon_driver_get_img_rdma_va() + 0x040)
#define PP_IMG_RDMA_FIFO_LOG_VA (hwtcon_driver_get_img_rdma_va() + 0x044)
#define PP_IMG_RDMA_DUMMY_VA (hwtcon_driver_get_img_rdma_va() + 0x090)
#define PP_IMG_RDMA_DEBUG_OUT_SEL_VA (hwtcon_driver_get_img_rdma_va() + 0x094)
#define PP_IMG_RDMA_MEM_START_ADDR_VA (hwtcon_driver_get_img_rdma_va() + 0xF00)
#define PP_IMG_RDMA_BG_CON_0_VA (hwtcon_driver_get_img_rdma_va() + 0x0a0)
#define PP_IMG_RDMA_BG_CON_1_VA (hwtcon_driver_get_img_rdma_va() + 0x0a4)
#define PP_IMG_RDMA_THRESHOLD_FOR_SODI_VA (hwtcon_driver_get_img_rdma_va() + \
	0x0a8)

/* WB_RDMA: 0x14009000 */
#define PP_WB_RDMA_INT_ENABLE_VA (hwtcon_driver_get_wb_rdma_va() + 0x000)
#define PP_WB_RDMA_INT_STATUS_VA (hwtcon_driver_get_wb_rdma_va() + 0x004)
#define PP_WB_RDMA_GLOBAL_CON_VA (hwtcon_driver_get_wb_rdma_va() + 0x010)
#define PP_WB_RDMA_SIZE_CON_0_VA (hwtcon_driver_get_wb_rdma_va() + 0x014)
#define PP_WB_RDMA_SIZE_CON_1_VA (hwtcon_driver_get_wb_rdma_va() + 0x018)
#define PP_WB_RDMA_TARGET_LINE_VA (hwtcon_driver_get_wb_rdma_va() + 0x01c)
#define PP_WB_RDMA_MEM_CON_VA (hwtcon_driver_get_wb_rdma_va() + 0x024)
#define PP_WB_RDMA_MEM_SRC_PITCH_VA (hwtcon_driver_get_wb_rdma_va() + 0x02C)
#define PP_WB_RDMA_MEM_GMC_SETTING_0_VA (hwtcon_driver_get_wb_rdma_va() + 0x030)
#define PP_WB_RDMA_MEM_SLOW_CON_VA (hwtcon_driver_get_wb_rdma_va() + 0x034)
#define PP_WB_RDMA_MEM_GMC_SETTING_1_VA (hwtcon_driver_get_wb_rdma_va() + 0x038)
#define PP_WB_RDMA_FIFO_CON_VA (hwtcon_driver_get_wb_rdma_va() + 0x040)
#define PP_WB_RDMA_FIFO_LOG_VA (hwtcon_driver_get_wb_rdma_va() + 0x044)
#define PP_WB_RDMA_DUMMY_VA (hwtcon_driver_get_wb_rdma_va() + 0x090)
#define PP_WB_RDMA_DEBUG_OUT_SEL_VA (hwtcon_driver_get_wb_rdma_va() + 0x094)
#define PP_WB_RDMA_MEM_START_ADDR_VA (hwtcon_driver_get_wb_rdma_va() + 0xF00)
#define PP_WB_RDMA_BG_CON_0_VA (hwtcon_driver_get_wb_rdma_va() + 0x0a0)
#define PP_WB_RDMA_BG_CON_1_VA (hwtcon_driver_get_wb_rdma_va() + 0x0a4)
#define PP_WB_RDMA_THRESHOLD_FOR_SODI_VA (hwtcon_driver_get_wb_rdma_va() + \
	0x0a8)

/* WB_WDMA: 0x1400A000 */
#define PP_WDMA_INTEN_VA (hwtcon_driver_get_wb_wdma_va() + 0x0)
#define PP_WDMA_INTSTA_VA (hwtcon_driver_get_wb_wdma_va() + 0x4)
#define PP_WDMA_EN_VA (hwtcon_driver_get_wb_wdma_va() + 0x8)
#define PP_WDMA_RST_VA (hwtcon_driver_get_wb_wdma_va() + 0xC)
#define PP_WDMA_SMI_CON_VA (hwtcon_driver_get_wb_wdma_va() + 0x10)
#define PP_WDMA_CFG_VA (hwtcon_driver_get_wb_wdma_va() + 0x14)
#define PP_WDMA_SRC_SIZE_VA (hwtcon_driver_get_wb_wdma_va() + 0x18)
#define PP_WDMA_CLIP_SIZE_VA (hwtcon_driver_get_wb_wdma_va() + 0x1C)
#define PP_WDMA_CLIP_COORD_VA (hwtcon_driver_get_wb_wdma_va() + 0x20)
#define PP_WDMA_DST_W_IN_BYTE_VA (hwtcon_driver_get_wb_wdma_va() + 0x28)
#define PP_WDMA_ALPHA_VA (hwtcon_driver_get_wb_wdma_va() + 0x2C)
#define PP_WDMA_BUF_CON1_VA (hwtcon_driver_get_wb_wdma_va() + 0x38)
#define PP_WDMA_BUF_CON2_VA (hwtcon_driver_get_wb_wdma_va() + 0x3C)
#define PP_WDMA_DST_UV_PITCH_VA (hwtcon_driver_get_wb_wdma_va() + 0x78)
#define PP_WDMA_DST_ADDR_OFFSET0_VA (hwtcon_driver_get_wb_wdma_va() + 0x80)
#define PP_WDMA_FLOW_CTRL_DBG_VA (hwtcon_driver_get_wb_wdma_va() + 0xA0)
#define PP_WDMA_EXEC_DBG_VA (hwtcon_driver_get_wb_wdma_va() + 0xA4)
#define PP_WDMA_CT_DBG_VA (hwtcon_driver_get_wb_wdma_va() + 0xA8)
#define PP_WDMA_SMI_TRAFFIC_DBG_VA (hwtcon_driver_get_wb_wdma_va() + 0xAC)
#define PP_WDMA_PROC_TRACK_DBG_0_VA (hwtcon_driver_get_wb_wdma_va() + 0xB0)
#define PP_WDMA_PROC_TRACK_DBG_1_VA (hwtcon_driver_get_wb_wdma_va() + 0xB4)
#define PP_WDMA_DEBUG_VA (hwtcon_driver_get_wb_wdma_va() + 0xB8)
#define PP_WDMA_DUMMY_VA (hwtcon_driver_get_wb_wdma_va() + 0x100)
#define PP_WDMA_DST_ADDR0_VA (hwtcon_driver_get_wb_wdma_va() + 0xF00)

/* PIPELINE: 0x1400B000 */
#define PIPELINE_LUT_CLR0_VA (hwtcon_driver_get_pipeline_va() + 0x00)
#define PIPELINE_LUT_CLR1_VA (hwtcon_driver_get_pipeline_va() + 0x04)
#define PIPELINE_COL_CLR0_VA (hwtcon_driver_get_pipeline_va() + 0x08)
#define PIPELINE_COL_CLR1_VA (hwtcon_driver_get_pipeline_va() + 0x0C)
#define PIPELINE_IMG_ACCESS_CFG0_VA (hwtcon_driver_get_pipeline_va() + 0x10)
#define PIPELINE_IMG_ACCESS_CFG1_VA (hwtcon_driver_get_pipeline_va() + 0x14)
#define PIPELINE__IRQ_CLR_VA (hwtcon_driver_get_pipeline_va() + 0x18)
#define PIPELINE_UPD_INFO_CLT0_VA (hwtcon_driver_get_pipeline_va() + 0x20)
#define PIPELINE_UPD_INFO_CLT1_VA (hwtcon_driver_get_pipeline_va() + 0X24)
#define PIPELINE_UPD_INFO_CLT2_VA (hwtcon_driver_get_pipeline_va() + 0x28)
#define PIPELINE_LUT_INFO_CLT0_VA (hwtcon_driver_get_pipeline_va() + 0x30)
#define PIPELINE_LUT_INFO_CLT1_VA (hwtcon_driver_get_pipeline_va() + 0x34)
#define PIPELINE_LUT_INFO_CLT2_VA (hwtcon_driver_get_pipeline_va() + 0x38)
#define PIPELINE_LUT_ARBIT_CFG_VA (hwtcon_driver_get_pipeline_va() + 0x40)
#define PIPELINE_LUT_ASSIGN_CFG_VA (hwtcon_driver_get_pipeline_va() + 0x44)
#define PIPELINE_COL_UPD_CFG0_VA (hwtcon_driver_get_pipeline_va() + 0x50)
#define PIPELINE_COL_UPD_CFG1_VA (hwtcon_driver_get_pipeline_va() + 0x54)
#define PIPELINE_COL_UPD_CFG2_VA (hwtcon_driver_get_pipeline_va() + 0x58)
#define PIPELINE_LUT_USE_CFG0_VA (hwtcon_driver_get_pipeline_va() + 0x60)
#define PIPELINE_LUT_USE_CFG1_VA (hwtcon_driver_get_pipeline_va() + 0x64)
#define PIPELINT_LUT_STATUS0_VA (hwtcon_driver_get_pipeline_va() + 0x100)
#define PIPELINT_LUT_STATUS1_VA (hwtcon_driver_get_pipeline_va() + 0x104)
#define PIPELINE_ASSIGN_STATUS0_VA (hwtcon_driver_get_pipeline_va() + 0x108)
#define PIPELINE_ASSIGN_STATUS1_VA (hwtcon_driver_get_pipeline_va() + 0x10C)
#define PIPELINE_COL_STATUS0_VA (hwtcon_driver_get_pipeline_va() + 0x110)
#define PIPELINE_COL_STATUS1_VA (hwtcon_driver_get_pipeline_va() + 0x114)
#define PIPELINE_COL_REGION_INFO0_VA (hwtcon_driver_get_pipeline_va() + 0x118)
#define PIPELINE_COL_REGION_INFO1_VA (hwtcon_driver_get_pipeline_va() + 0x11C)
#define PIPELINE_UPD_STATUS_VA (hwtcon_driver_get_pipeline_va() + 0x120)
#define PIPELINE_LUT_INFO_STA0_VA (hwtcon_driver_get_pipeline_va() + 0x124)
#define PIPELINE_LUT_INFO_STA1_VA (hwtcon_driver_get_pipeline_va() + 0x128)
#define PIPELINE_LUT_INFO_STA2_VA (hwtcon_driver_get_pipeline_va() + 0x12C)
#define PIPELINE_PXL_COL_RGN0_VA (hwtcon_driver_get_pipeline_va() + 0x130)
#define PIPELINE_PXL_COL_RGN1_VA (hwtcon_driver_get_pipeline_va() + 0x134)
#define PIPELINE_PXL_UPD_RGN0_VA (hwtcon_driver_get_pipeline_va() + 0x138)
#define PIPELINE_PXL_UPD_RGN1_VA (hwtcon_driver_get_pipeline_va() + 0x13C)
#define PIPELINE_UPD_INFO0_VA (hwtcon_driver_get_pipeline_va() + 0x140)
#define PIPELINE_UPD_INFO1_VA (hwtcon_driver_get_pipeline_va() + 0x144)

/* PAPER_TOP: 0x1400D000 */
#define PAPER_TCTOP_PWDC_CTL_VA (hwtcon_driver_get_paper_top_va() + 0x00)
#define PAPER_TCTOP_MAIN_CTL_VA (hwtcon_driver_get_paper_top_va() + 0x04)
#define PAPER_TCTOP_INI_CFG_VA (hwtcon_driver_get_paper_top_va() + 0x08)
#define PAPER_TCTOP_PANEL_SIZE_VA (hwtcon_driver_get_paper_top_va() + 0x0C)
#define PAPER_TCTOP_REGAL_CFG_VA (hwtcon_driver_get_paper_top_va() + 0x10)
#define PAPET_TCTOP_FIFO_CFG_VA (hwtcon_driver_get_paper_top_va() + 0x14)
#define PAPER_TCTOP_DPI_CFG_VA (hwtcon_driver_get_paper_top_va() + 0x18)
#define PAPER_TCTOP_UPD_CFG0_VA (hwtcon_driver_get_paper_top_va() + 0X20)
#define PAPER_TCTOP_UPD_CFG1_VA (hwtcon_driver_get_paper_top_va() + 0x24)
#define PAPER_TCTOP_UPD_CFG2_VA (hwtcon_driver_get_paper_top_va() + 0x28)
#define PAPER_TCTOP_UPD_CFG3_VA (hwtcon_driver_get_paper_top_va() + 0x2C)
#define PAPER_TCTOP_UPD_CFG4_VA (hwtcon_driver_get_paper_top_va() + 0x30)
#define PAPER_TCTOP_UPD_CFG5_VA (hwtcon_driver_get_paper_top_va() + 0x34)
#define PAPER_TCTOP_SOF_CTL_VA (hwtcon_driver_get_paper_top_va() + 0x40)
#define PAPER_TCTOP_SOF_MAIN_CTL_VA (hwtcon_driver_get_paper_top_va() + 0x44)
#define PAPER_TCTOP_SOF_PIPELINE_CTL_VA (hwtcon_driver_get_paper_top_va() + \
	0x48)
#define PAPER_TCTOP_SOF_WF_LUT_CTL_VA (hwtcon_driver_get_paper_top_va() + 0x4C)
#define PAPER_TCTOP_SOF_DMA_CTL_VA (hwtcon_driver_get_paper_top_va() + 0x50)
#define PAPER_TCTOP_SOF_MERGE_CTL_VA (hwtcon_driver_get_paper_top_va() + 0x54)
#define PAPER_TCTOP_SOF_DISP_RDMA_CTL_VA (hwtcon_driver_get_paper_top_va() + \
	0x58)
#define PAPER_TCTOP_BUF_CFG0_VA (hwtcon_driver_get_paper_top_va() + 0x60)
#define PAPER_TCTOP_BUF_CFG1_VA (hwtcon_driver_get_paper_top_va() + 0x64)
#define PAPER_TCTOP_HIST_CFG0_VA (hwtcon_driver_get_paper_top_va() + 0x70)
#define PAPER_TCTOP_HIST_CFG1_VA (hwtcon_driver_get_paper_top_va() + 0x74)
#define PAPER_TCTOP_HIST_CFG2_VA (hwtcon_driver_get_paper_top_va() + 0x78)
#define PAPER_TCTOP_HIST_CFG3_VA (hwtcon_driver_get_paper_top_va() + 0x7C)
#define PAPER_TCTOP_HIST_CFG4_VA (hwtcon_driver_get_paper_top_va() + 0x80)
#define PAPER_TCTOP_HIST_STA0_VA (hwtcon_driver_get_paper_top_va() + 0x84)
#define PAPER_TCTOP_HIST_STA1_VA (hwtcon_driver_get_paper_top_va() + 0x88)
#define PAPER_TCTOP_HIST_STA2_VA (hwtcon_driver_get_paper_top_va() + 0x8C)
#define PAPER_TCTOP_STATUS_VA (hwtcon_driver_get_paper_top_va() + 0x90)
#define PAPER_UPD_IMG_STA0_VA (hwtcon_driver_get_paper_top_va() + 0x94)
#define PAPER_UPD_IMG_STA1_VA (hwtcon_driver_get_paper_top_va() + 0x98)
#define PAPER_TCTOP_PIN_SWAP0_VA (hwtcon_driver_get_paper_top_va() + 0xA0)
#define PAPER_TCTOP_PIN_SWAP1_VA (hwtcon_driver_get_paper_top_va() + 0xA4)
#define PAPER_TCTOP_PIN_SWAP2_VA (hwtcon_driver_get_paper_top_va() + 0xA8)
#define PAPER_TCTOP_PIN_SWAP3_VA (hwtcon_driver_get_paper_top_va() + 0xAC)
#define PAPER_TCTOP_PIN_SWAP4_VA (hwtcon_driver_get_paper_top_va() + 0xB0)
#define PAPER_TCTOP_PIN_SWAP5_VA (hwtcon_driver_get_paper_top_va() + 0xB4)
#define PAPER_TCTOP_PIN_INV_VA (hwtcon_driver_get_paper_top_va() + 0xB8)
#define PAPER_TCTOP_TCON_FRAME_COUNT_VA (hwtcon_driver_get_paper_top_va() + \
	0xC0)

#define PAPER_TCTOP_WB_ST_ADDR0_VA (hwtcon_driver_get_paper_top_va() + 0xF00)
#define PAPER_TCTOP_WB_ST_ADDR1_VA (hwtcon_driver_get_paper_top_va() + 0xF04)
#define PAPER_TCTOP_IMG_ST_ADDR_VA (hwtcon_driver_get_paper_top_va() + 0xF08)

/* PA define */

/* IMG_RDMA: 0x14008000 */
#define PP_IMG_RDMA_INT_ENABLE (hwtcon_driver_get_img_rdma_pa() + 0x000)
#define PP_IMG_RDMA_INT_STATUS (hwtcon_driver_get_img_rdma_pa() + 0x004)
#define PP_IMG_RDMA_GLOBAL_CON (hwtcon_driver_get_img_rdma_pa() + 0x010)
#define PP_IMG_RDMA_SIZE_CON_0 (hwtcon_driver_get_img_rdma_pa() + 0x014)
#define PP_IMG_RDMA_SIZE_CON_1 (hwtcon_driver_get_img_rdma_pa() + 0x018)
#define PP_IMG_RDMA_TARGET_LINE (hwtcon_driver_get_img_rdma_pa() + 0x01c)
#define PP_IMG_RDMA_MEM_CON (hwtcon_driver_get_img_rdma_pa() + 0x024)
#define PP_IMG_RDMA_MEM_SRC_PITCH (hwtcon_driver_get_img_rdma_pa() + 0x02C)
#define PP_IMG_RDMA_MEM_GMC_SETTING_0 (hwtcon_driver_get_img_rdma_pa() + 0x030)
#define PP_IMG_RDMA_MEM_SLOW_CON (hwtcon_driver_get_img_rdma_pa() + 0x034)
#define PP_IMG_RDMA_MEM_GMC_SETTING_1 (hwtcon_driver_get_img_rdma_pa() + 0x038)
#define PP_IMG_RDMA_FIFO_CON (hwtcon_driver_get_img_rdma_pa() + 0x040)
#define PP_IMG_RDMA_FIFO_LOG (hwtcon_driver_get_img_rdma_pa() + 0x044)
#define PP_IMG_RDMA_DUMMY (hwtcon_driver_get_img_rdma_pa() + 0x090)
#define PP_IMG_RDMA_DEBUG_OUT_SEL (hwtcon_driver_get_img_rdma_pa() + 0x094)
#define PP_IMG_RDMA_MEM_START_ADDR (hwtcon_driver_get_img_rdma_pa() + 0xF00)
#define PP_IMG_RDMA_BG_CON_0 (hwtcon_driver_get_img_rdma_pa() + 0x0a0)
#define PP_IMG_RDMA_BG_CON_1 (hwtcon_driver_get_img_rdma_pa() + 0x0a4)
#define PP_IMG_RDMA_THRESHOLD_FOR_SODI (hwtcon_driver_get_img_rdma_pa() + 0x0a8)

/* WB_RDMA: 0x14009000 */
#define PP_WB_RDMA_INT_ENABLE (hwtcon_driver_get_wb_rdma_pa() + 0x000)
#define PP_WB_RDMA_INT_STATUS (hwtcon_driver_get_wb_rdma_pa() + 0x004)
#define PP_WB_RDMA_GLOBAL_CON (hwtcon_driver_get_wb_rdma_pa() + 0x010)
#define PP_WB_RDMA_SIZE_CON_0 (hwtcon_driver_get_wb_rdma_pa() + 0x014)
#define PP_WB_RDMA_SIZE_CON_1 (hwtcon_driver_get_wb_rdma_pa() + 0x018)
#define PP_WB_RDMA_TARGET_LINE (hwtcon_driver_get_wb_rdma_pa() + 0x01c)
#define PP_WB_RDMA_MEM_CON (hwtcon_driver_get_wb_rdma_pa() + 0x024)
#define PP_WB_RDMA_MEM_SRC_PITCH (hwtcon_driver_get_wb_rdma_pa() + 0x02C)
#define PP_WB_RDMA_MEM_GMC_SETTING_0 (hwtcon_driver_get_wb_rdma_pa() + 0x030)
#define PP_WB_RDMA_MEM_SLOW_CON (hwtcon_driver_get_wb_rdma_pa() + 0x034)
#define PP_WB_RDMA_MEM_GMC_SETTING_1 (hwtcon_driver_get_wb_rdma_pa() + 0x038)
#define PP_WB_RDMA_FIFO_CON (hwtcon_driver_get_wb_rdma_pa() + 0x040)
#define PP_WB_RDMA_FIFO_LOG (hwtcon_driver_get_wb_rdma_pa() + 0x044)
#define PP_WB_RDMA_DUMMY (hwtcon_driver_get_wb_rdma_pa() + 0x090)
#define PP_WB_RDMA_DEBUG_OUT_SEL (hwtcon_driver_get_wb_rdma_pa() + 0x094)
#define PP_WB_RDMA_MEM_START_ADDR (hwtcon_driver_get_wb_rdma_pa() + 0xF00)
#define PP_WB_RDMA_BG_CON_0 (hwtcon_driver_get_wb_rdma_pa() + 0x0a0)
#define PP_WB_RDMA_BG_CON_1 (hwtcon_driver_get_wb_rdma_pa() + 0x0a4)
#define PP_WB_RDMA_THRESHOLD_FOR_SODI (hwtcon_driver_get_wb_rdma_pa() + 0x0a8)

/* WB_WDMA: 0x1400A000 */
#define PP_WDMA_INTEN (hwtcon_driver_get_wb_wdma_pa() + 0x0)
#define PP_WDMA_INTSTA (hwtcon_driver_get_wb_wdma_pa() + 0x4)
#define PP_WDMA_EN (hwtcon_driver_get_wb_wdma_pa() + 0x8)
#define PP_WDMA_RST (hwtcon_driver_get_wb_wdma_pa() + 0xC)
#define PP_WDMA_SMI_CON (hwtcon_driver_get_wb_wdma_pa() + 0x10)
#define PP_WDMA_CFG (hwtcon_driver_get_wb_wdma_pa() + 0x14)
#define PP_WDMA_SRC_SIZE (hwtcon_driver_get_wb_wdma_pa() + 0x18)
#define PP_WDMA_CLIP_SIZE (hwtcon_driver_get_wb_wdma_pa() + 0x1C)
#define PP_WDMA_CLIP_COORD (hwtcon_driver_get_wb_wdma_pa() + 0x20)
#define PP_WDMA_DST_W_IN_BYTE (hwtcon_driver_get_wb_wdma_pa() + 0x28)
#define PP_WDMA_ALPHA (hwtcon_driver_get_wb_wdma_pa() + 0x2C)
#define PP_WDMA_BUF_CON1 (hwtcon_driver_get_wb_wdma_pa() + 0x38)
#define PP_WDMA_BUF_CON2 (hwtcon_driver_get_wb_wdma_pa() + 0x3C)
#define PP_WDMA_DST_UV_PITCH (hwtcon_driver_get_wb_wdma_pa() + 0x78)
#define PP_WDMA_DST_ADDR_OFFSET0 (hwtcon_driver_get_wb_wdma_pa() + 0x80)
#define PP_WDMA_FLOW_CTRL_DBG (hwtcon_driver_get_wb_wdma_pa() + 0xA0)
#define PP_WDMA_EXEC_DBG (hwtcon_driver_get_wb_wdma_pa() + 0xA4)
#define PP_WDMA_CT_DBG (hwtcon_driver_get_wb_wdma_pa() + 0xA8)
#define PP_WDMA_SMI_TRAFFIC_DBG (hwtcon_driver_get_wb_wdma_pa() + 0xAC)
#define PP_WDMA_PROC_TRACK_DBG_0 (hwtcon_driver_get_wb_wdma_pa() + 0xB0)
#define PP_WDMA_PROC_TRACK_DBG_1 (hwtcon_driver_get_wb_wdma_pa() + 0xB4)
#define PP_WDMA_DEBUG (hwtcon_driver_get_wb_wdma_pa() + 0xB8)
#define PP_WDMA_DUMMY (hwtcon_driver_get_wb_wdma_pa() + 0x100)
#define PP_WDMA_DST_ADDR0 (hwtcon_driver_get_wb_wdma_pa() + 0xF00)

/* PIPELINE: 0x1400B000 */
#define PIPELINE_LUT_CLR0 (hwtcon_driver_get_pipeline_pa() + 0x00)
#define PIPELINE_LUT_CLR1 (hwtcon_driver_get_pipeline_pa() + 0x04)
#define PIPELINE_COL_CLR0 (hwtcon_driver_get_pipeline_pa() + 0x08)
#define PIPELINE_COL_CLR1 (hwtcon_driver_get_pipeline_pa() + 0x0C)
#define PIPELINE_IMG_ACCESS_CFG0 (hwtcon_driver_get_pipeline_pa() + 0x10)
#define PIPELINE_IMG_ACCESS_CFG1 (hwtcon_driver_get_pipeline_pa() + 0x14)
#define PIPELINE__IRQ_CLR (hwtcon_driver_get_pipeline_pa() + 0x18)
#define PIPELINE_UPD_INFO_CLT0 (hwtcon_driver_get_pipeline_pa() + 0x20)
#define PIPELINE_UPD_INFO_CLT1 (hwtcon_driver_get_pipeline_pa() + 0X24)
#define PIPELINE_UPD_INFO_CLT2 (hwtcon_driver_get_pipeline_pa() + 0x28)
#define PIPELINE_LUT_INFO_CLT0 (hwtcon_driver_get_pipeline_pa() + 0x30)
#define PIPELINE_LUT_INFO_CLT1 (hwtcon_driver_get_pipeline_pa() + 0x34)
#define PIPELINE_LUT_INFO_CLT2 (hwtcon_driver_get_pipeline_pa() + 0x38)
#define PIPELINE_LUT_ARBIT_CFG (hwtcon_driver_get_pipeline_pa() + 0x40)
#define PIPELINE_LUT_ASSIGN_CFG (hwtcon_driver_get_pipeline_pa() + 0x44)
#define PIPELINE_COL_UPD_CFG0 (hwtcon_driver_get_pipeline_pa() + 0x50)
#define PIPELINE_COL_UPD_CFG1 (hwtcon_driver_get_pipeline_pa() + 0x54)
#define PIPELINE_COL_UPD_CFG2 (hwtcon_driver_get_pipeline_pa() + 0x58)
#define PIPELINE_LUT_USE_CFG0 (hwtcon_driver_get_pipeline_pa() + 0x60)
#define PIPELINE_LUT_USE_CFG1 (hwtcon_driver_get_pipeline_pa() + 0x64)
#define PIPELINT_LUT_STATUS0 (hwtcon_driver_get_pipeline_pa() + 0x100)
#define PIPELINT_LUT_STATUS1 (hwtcon_driver_get_pipeline_pa() + 0x104)
#define PIPELINE_ASSIGN_STATUS0 (hwtcon_driver_get_pipeline_pa() + 0x108)
#define PIPELINE_ASSIGN_STATUS1 (hwtcon_driver_get_pipeline_pa() + 0x10C)
#define PIPELINE_COL_STATUS0 (hwtcon_driver_get_pipeline_pa() + 0x110)
#define PIPELINE_COL_STATUS1 (hwtcon_driver_get_pipeline_pa() + 0x114)
#define PIPELINE_COL_REGION_INFO0 (hwtcon_driver_get_pipeline_pa() + 0x118)
#define PIPELINE_COL_REGION_INFO1 (hwtcon_driver_get_pipeline_pa() + 0x11C)
#define PIPELINE_UPD_STATUS (hwtcon_driver_get_pipeline_pa() + 0x120)
#define PIPELINE_LUT_INFO_STA0 (hwtcon_driver_get_pipeline_pa() + 0x124)
#define PIPELINE_LUT_INFO_STA1 (hwtcon_driver_get_pipeline_pa() + 0x128)
#define PIPELINE_LUT_INFO_STA2 (hwtcon_driver_get_pipeline_pa() + 0x12C)
#define PIPELINE_PXL_COL_RGN0 (hwtcon_driver_get_pipeline_pa() + 0x130)
#define PIPELINE_PXL_COL_RGN1 (hwtcon_driver_get_pipeline_pa() + 0x134)
#define PIPELINE_PXL_UPD_RGN0 (hwtcon_driver_get_pipeline_pa() + 0x138)
#define PIPELINE_PXL_UPD_RGN1 (hwtcon_driver_get_pipeline_pa() + 0x13C)
#define PIPELINE_UPD_INFO0 (hwtcon_driver_get_pipeline_pa() + 0x140)
#define PIPELINE_UPD_INFO1 (hwtcon_driver_get_pipeline_pa() + 0x144)

/* PAPER_TOP: 0x1400D000 */
#define PAPER_TCTOP_PWDC_CTL (hwtcon_driver_get_paper_top_pa() + 0x00)
#define PAPER_TCTOP_MAIN_CTL (hwtcon_driver_get_paper_top_pa() + 0x04)
#define PAPER_TCTOP_INI_CFG (hwtcon_driver_get_paper_top_pa() + 0x08)
#define PAPER_TCTOP_PANEL_SIZE (hwtcon_driver_get_paper_top_pa() + 0x0C)
#define PAPER_TCTOP_REGAL_CFG (hwtcon_driver_get_paper_top_pa() + 0x10)
#define PAPET_TCTOP_FIFO_CFG (hwtcon_driver_get_paper_top_pa() + 0x14)
#define PAPER_TCTOP_DPI_CFG (hwtcon_driver_get_paper_top_pa() + 0x18)
#define PAPER_TCTOP_UPD_CFG0 (hwtcon_driver_get_paper_top_pa() + 0X20)
#define PAPER_TCTOP_UPD_CFG1 (hwtcon_driver_get_paper_top_pa() + 0x24)
#define PAPER_TCTOP_UPD_CFG2 (hwtcon_driver_get_paper_top_pa() + 0x28)
#define PAPER_TCTOP_UPD_CFG3 (hwtcon_driver_get_paper_top_pa() + 0x2C)
#define PAPER_TCTOP_UPD_CFG4 (hwtcon_driver_get_paper_top_pa() + 0x30)
#define PAPER_TCTOP_UPD_CFG5 (hwtcon_driver_get_paper_top_pa() + 0x34)
#define PAPER_TCTOP_SOF_CTL (hwtcon_driver_get_paper_top_pa() + 0x40)
#define PAPER_TCTOP_SOF_MAIN_CTL (hwtcon_driver_get_paper_top_pa() + 0x44)
#define PAPER_TCTOP_SOF_PIPELINE_CTL (hwtcon_driver_get_paper_top_pa() + 0x48)
#define PAPER_TCTOP_SOF_WF_LUT_CTL (hwtcon_driver_get_paper_top_pa() + 0x4C)
#define PAPER_TCTOP_SOF_DMA_CTL (hwtcon_driver_get_paper_top_pa() + 0x50)
#define PAPER_TCTOP_SOF_MERGE_CTL (hwtcon_driver_get_paper_top_pa() + 0x54)
#define PAPER_TCTOP_SOF_DISP_RDMA_CTL (hwtcon_driver_get_paper_top_pa() + 0x58)
#define PAPER_TCTOP_BUF_CFG0 (hwtcon_driver_get_paper_top_pa() + 0x60)
#define PAPER_TCTOP_BUF_CFG1 (hwtcon_driver_get_paper_top_pa() + 0x64)
#define PAPER_TCTOP_HIST_CFG0 (hwtcon_driver_get_paper_top_pa() + 0x70)
#define PAPER_TCTOP_HIST_CFG1 (hwtcon_driver_get_paper_top_pa() + 0x74)
#define PAPER_TCTOP_HIST_CFG2 (hwtcon_driver_get_paper_top_pa() + 0x78)
#define PAPER_TCTOP_HIST_CFG3 (hwtcon_driver_get_paper_top_pa() + 0x7C)
#define PAPER_TCTOP_HIST_CFG4 (hwtcon_driver_get_paper_top_pa() + 0x80)
#define PAPER_TCTOP_HIST_STA0 (hwtcon_driver_get_paper_top_pa() + 0x84)
#define PAPER_TCTOP_HIST_STA1 (hwtcon_driver_get_paper_top_pa() + 0x88)
#define PAPER_TCTOP_HIST_STA2 (hwtcon_driver_get_paper_top_pa() + 0x8C)
#define PAPER_TCTOP_STATUS (hwtcon_driver_get_paper_top_pa() + 0x90)
#define PAPER_UPD_IMG_STA0 (hwtcon_driver_get_paper_top_pa() + 0x94)
#define PAPER_UPD_IMG_STA1 (hwtcon_driver_get_paper_top_pa() + 0x98)
#define PAPER_TCTOP_PIN_SWAP0 (hwtcon_driver_get_paper_top_pa() + 0xA0)
#define PAPER_TCTOP_PIN_SWAP1 (hwtcon_driver_get_paper_top_pa() + 0xA4)
#define PAPER_TCTOP_PIN_SWAP2 (hwtcon_driver_get_paper_top_pa() + 0xA8)
#define PAPER_TCTOP_PIN_SWAP3 (hwtcon_driver_get_paper_top_pa() + 0xAC)
#define PAPER_TCTOP_PIN_SWAP4 (hwtcon_driver_get_paper_top_pa() + 0xB0)
#define PAPER_TCTOP_PIN_SWAP5 (hwtcon_driver_get_paper_top_pa() + 0xB4)
#define PAPER_TCTOP_PIN_INV (hwtcon_driver_get_paper_top_pa() + 0xB8)
#define PAPER_TCTOP_TCON_FRAME_COUNT (hwtcon_driver_get_paper_top_pa() + 0xC0)
#define PAPER_TCTOP_WB_ST_ADDR0 (hwtcon_driver_get_paper_top_pa() + 0xF00)
#define PAPER_TCTOP_WB_ST_ADDR1 (hwtcon_driver_get_paper_top_pa() + 0xF04)
#define PAPER_TCTOP_IMG_ST_ADDR (hwtcon_driver_get_paper_top_pa() + 0xF08)

/* WF_LUT_RDMA: 0x14005000 */
#define WF_LUT_RDMA_INT_ENABLE (hwtcon_driver_get_wf_lut_rdma_pa() + 0x000)
#define WF_LUT_RDMA_INT_STATUS (hwtcon_driver_get_wf_lut_rdma_pa() + 0x004)
#define WF_LUT_RDMA_INT_STATUS_VA (hwtcon_driver_get_wf_lut_rdma_va() + 0x004)
#define WF_LUT_RDMA_GLOBAL_CON (hwtcon_driver_get_wf_lut_rdma_pa() + 0x010)
#define WF_LUT_RDMA_SIZE_CON_0 (hwtcon_driver_get_wf_lut_rdma_pa() + 0x014)
#define WF_LUT_RDMA_SIZE_CON_1 (hwtcon_driver_get_wf_lut_rdma_pa() + 0x018)
#define WF_LUT_RDMA_TARGET_LINE (hwtcon_driver_get_wf_lut_rdma_pa() + 0x01c)
#define WF_LUT_RDMA_MEM_CON (hwtcon_driver_get_wf_lut_rdma_pa() + 0x024)
#define WF_LUT_RDMA_MEM_SRC_PITCH (hwtcon_driver_get_wf_lut_rdma_pa() + 0x02C)
#define WF_LUT_RDMA_MEM_GMC_SETTING_0 (hwtcon_driver_get_wf_lut_rdma_pa() + \
	0x030)
#define WF_LUT_RDMA_MEM_SLOW_CON (hwtcon_driver_get_wf_lut_rdma_pa() + 0x034)
#define WF_LUT_RDMA_MEM_GMC_SETTING_1 (hwtcon_driver_get_wf_lut_rdma_pa() + \
	0x038)
#define WF_LUT_RDMA_FIFO_CON (hwtcon_driver_get_wf_lut_rdma_pa() + 0x040)
#define WF_LUT_RDMA_FIFO_LOG (hwtcon_driver_get_wf_lut_rdma_pa() + 0x044)
#define WF_LUT_RDMA_DUMMY (hwtcon_driver_get_wf_lut_rdma_pa() + 0x090)
#define WF_LUT_RDMA_DEBUG_OUT_SEL (hwtcon_driver_get_wf_lut_rdma_pa() + 0x094)
#define WF_LUT_RDMA_MEM_START_ADDR (hwtcon_driver_get_wf_lut_rdma_pa() + 0xF00)
#define WF_LUT_RDMA_BG_CON_0 (hwtcon_driver_get_wf_lut_rdma_pa() + 0x0a0)
#define WF_LUT_RDMA_BG_CON_1 (hwtcon_driver_get_wf_lut_rdma_pa() + 0x0a4)
#define WF_LUT_RDMA_THRESHOLD_FOR_SODI (hwtcon_driver_get_wf_lut_rdma_pa() + \
	0x0a8)

/* DPI: 0x14006000 */
#define WF_LUT_DPI_EN (hwtcon_driver_get_wf_lut_dpi_pa() + 0x000)
#define WF_LUT_DPI_RST (hwtcon_driver_get_wf_lut_dpi_pa() + 0x004)
#define WF_LUT_DPI_INTEN (hwtcon_driver_get_wf_lut_dpi_pa() + 0x008)
#define WF_LUT_DPI_INTSTA (hwtcon_driver_get_wf_lut_dpi_pa() + 0x00C)
#define WF_LUT_DPI_INTSTA_VA (hwtcon_driver_get_wf_lut_dpi_va() + 0x00C)
#define WF_LUT_DPI_OUTPUT_SETTING (hwtcon_driver_get_wf_lut_dpi_pa() + 0x014)
#define WF_LUT_DPI_SIZE (hwtcon_driver_get_wf_lut_dpi_pa() + 0x018)
#define WF_LUT_DPI_TGEN_HWIDTH (hwtcon_driver_get_wf_lut_dpi_pa() + 0x020)
#define WF_LUT_DPI_TGEN_HPORCH (hwtcon_driver_get_wf_lut_dpi_pa() + 0x024)
#define WF_LUT_DPI_TGEN_VWIDTH (hwtcon_driver_get_wf_lut_dpi_pa() + 0x028)
#define WF_LUT_DPI_TGEN_VPORCH (hwtcon_driver_get_wf_lut_dpi_pa() + 0x02C)
#define WF_LUT_DPI_STATUS (hwtcon_driver_get_wf_lut_dpi_pa() + 0x040)
#define WF_LUT_DPI_TMODE (hwtcon_driver_get_wf_lut_dpi_pa() + 0x044)
#define WF_LUT_DPI_CHECKSUM (hwtcon_driver_get_wf_lut_dpi_pa() + 0x048)
#define WF_LUT_DPI_CHECKSUM_VA (hwtcon_driver_get_wf_lut_dpi_va() + 0x048)
#define WF_LUT_DPI_MUTEX_VSYNC_SETTING (hwtcon_driver_get_wf_lut_dpi_pa() + \
	0x0E0)

/* TCON: 0x14007000 */
#define TCON_GR0 (hwtcon_driver_get_tcon_pa() + 0x000)
#define TCON_GR1 (hwtcon_driver_get_tcon_pa() + 0x004)
#define TCON_GR2 (hwtcon_driver_get_tcon_pa() + 0x008)
#define TCON_GR3 (hwtcon_driver_get_tcon_pa() + 0x00C)
#define TCON_TIM0R0 (hwtcon_driver_get_tcon_pa() + 0x040)
#define TCON_TIM0R1 (hwtcon_driver_get_tcon_pa() + 0x044)
#define TCON_TIM0R2 (hwtcon_driver_get_tcon_pa() + 0x048)
#define TCON_TIM0R3 (hwtcon_driver_get_tcon_pa() + 0x04C)
#define TCON_TIM0R4 (hwtcon_driver_get_tcon_pa() + 0x050)
#define TCON_TIM0R5 (hwtcon_driver_get_tcon_pa() + 0x054)
#define TCON_TIM0R6 (hwtcon_driver_get_tcon_pa() + 0x058)
#define TCON_TIM0R7 (hwtcon_driver_get_tcon_pa() + 0x05C)
#define TCON_TIM1R0 (hwtcon_driver_get_tcon_pa() + 0x060)
#define TCON_TIM1R1 (hwtcon_driver_get_tcon_pa() + 0x064)
#define TCON_TIM1R2 (hwtcon_driver_get_tcon_pa() + 0x068)
#define TCON_TIM1R3 (hwtcon_driver_get_tcon_pa() + 0x06C)
#define TCON_TIM1R4 (hwtcon_driver_get_tcon_pa() + 0x070)
#define TCON_TIM1R5 (hwtcon_driver_get_tcon_pa() + 0x074)
#define TCON_TIM1R6 (hwtcon_driver_get_tcon_pa() + 0x078)
#define TCON_TIM1R7 (hwtcon_driver_get_tcon_pa() + 0x07C)
#define TCON_TIM2R0 (hwtcon_driver_get_tcon_pa() + 0x080)
#define TCON_TIM2R1 (hwtcon_driver_get_tcon_pa() + 0x084)
#define TCON_TIM2R2 (hwtcon_driver_get_tcon_pa() + 0x088)
#define TCON_TIM2R3 (hwtcon_driver_get_tcon_pa() + 0x08C)
#define TCON_TIM2R4 (hwtcon_driver_get_tcon_pa() + 0x090)
#define TCON_TIM2R5 (hwtcon_driver_get_tcon_pa() + 0x094)
#define TCON_TIM2R6 (hwtcon_driver_get_tcon_pa() + 0x098)
#define TCON_TIM2R7 (hwtcon_driver_get_tcon_pa() + 0x09C)
#define TCON_TIM3R0 (hwtcon_driver_get_tcon_pa() + 0x0A0)
#define TCON_TIM3R1 (hwtcon_driver_get_tcon_pa() + 0x0A4)
#define TCON_TIM3R2 (hwtcon_driver_get_tcon_pa() + 0x0A8)
#define TCON_TIM3R3 (hwtcon_driver_get_tcon_pa() + 0x0AC)
#define TCON_TIM3R4 (hwtcon_driver_get_tcon_pa() + 0x0B0)
#define TCON_TIM3R5 (hwtcon_driver_get_tcon_pa() + 0x0B4)
#define TCON_TIM3R6 (hwtcon_driver_get_tcon_pa() + 0x0B8)
#define TCON_TIM3R7 (hwtcon_driver_get_tcon_pa() + 0x0BC)
#define TCON_TIM4R0 (hwtcon_driver_get_tcon_pa() + 0x0C0)
#define TCON_TIM4R1 (hwtcon_driver_get_tcon_pa() + 0x0C4)
#define TCON_TIM4R2 (hwtcon_driver_get_tcon_pa() + 0x0C8)
#define TCON_TIM4R3 (hwtcon_driver_get_tcon_pa() + 0x0CC)
#define TCON_TIM4R4 (hwtcon_driver_get_tcon_pa() + 0x0D0)
#define TCON_TIM4R5 (hwtcon_driver_get_tcon_pa() + 0x0D4)
#define TCON_TIM4R6 (hwtcon_driver_get_tcon_pa() + 0x0D8)
#define TCON_TIM4R7 (hwtcon_driver_get_tcon_pa() + 0x0DC)
#define TCON_TIM5R0 (hwtcon_driver_get_tcon_pa() + 0x0E0)
#define TCON_TIM5R1 (hwtcon_driver_get_tcon_pa() + 0x0E4)
#define TCON_TIM5R2 (hwtcon_driver_get_tcon_pa() + 0x0E8)
#define TCON_TIM5R3 (hwtcon_driver_get_tcon_pa() + 0x0EC)
#define TCON_TIM5R4 (hwtcon_driver_get_tcon_pa() + 0x0F0)
#define TCON_TIM5R5 (hwtcon_driver_get_tcon_pa() + 0x0F4)
#define TCON_TIM5R6 (hwtcon_driver_get_tcon_pa() + 0x0F8)
#define TCON_TIM5R7 (hwtcon_driver_get_tcon_pa() + 0x0FC)
#define TCON_TIM6R0 (hwtcon_driver_get_tcon_pa() + 0x100)
#define TCON_TIM6R1 (hwtcon_driver_get_tcon_pa() + 0x104)
#define TCON_TIM6R2 (hwtcon_driver_get_tcon_pa() + 0x108)
#define TCON_TIM6R3 (hwtcon_driver_get_tcon_pa() + 0x10C)
#define TCON_TIM6R4 (hwtcon_driver_get_tcon_pa() + 0x110)
#define TCON_TIM6R5 (hwtcon_driver_get_tcon_pa() + 0x114)
#define TCON_TIM6R6 (hwtcon_driver_get_tcon_pa() + 0x118)
#define TCON_TIM6R7 (hwtcon_driver_get_tcon_pa() + 0x11C)
#define TCON_TIM7R0 (hwtcon_driver_get_tcon_pa() + 0x120)
#define TCON_TIM7R1 (hwtcon_driver_get_tcon_pa() + 0x124)
#define TCON_TIM7R2 (hwtcon_driver_get_tcon_pa() + 0x128)
#define TCON_TIM7R3 (hwtcon_driver_get_tcon_pa() + 0x12C)
#define TCON_TIM7R4 (hwtcon_driver_get_tcon_pa() + 0x130)
#define TCON_TIM7R5 (hwtcon_driver_get_tcon_pa() + 0x134)
#define TCON_TIM7R6 (hwtcon_driver_get_tcon_pa() + 0x138)
#define TCON_TIM7R7 (hwtcon_driver_get_tcon_pa() + 0x13C)

/* mmsys: 0x14000000 */
#define MMSYS_DUMMY1 (hwtcon_driver_get_mmsys_pa() + 0x404)
#define MMSYS_MDP_DL_CFG_WD (hwtcon_driver_get_mmsys_pa() + 0x934)

/* wf_lut: 0x14004000 */
#define WF_LUT_STA (hwtcon_driver_get_wf_lut_pa() + 0x00)
#define WF_LUT_INTEN (hwtcon_driver_get_wf_lut_pa() + 0x04)
#define WF_LUT_INTSTA (hwtcon_driver_get_wf_lut_pa() + 0x08)
#define WF_LUT_INTSTA_VA (hwtcon_driver_get_wf_lut_va() + 0x08)
#define WF_LUT_EN (hwtcon_driver_get_wf_lut_pa() + 0x0C)
#define WF_LUT_TRIG (hwtcon_driver_get_wf_lut_pa() + 0x10)
#define WF_LUT_RST (hwtcon_driver_get_wf_lut_pa() + 0x14)
#define WF_LUT_ROI_SIZE (hwtcon_driver_get_wf_lut_pa() + 0x20)
#define WF_LUT_DATAPATH_CON (hwtcon_driver_get_wf_lut_pa() + 0X24)
#define WF_LUT_SRC_CON (hwtcon_driver_get_wf_lut_pa() + 0x2C)
#define WF_LUT_L0_CON (hwtcon_driver_get_wf_lut_pa() + 0x30)
#define WF_LUT_L0_SRC_SIZE (hwtcon_driver_get_wf_lut_pa() + 0x38)
#define WF_LUT_L0_OFFSET (hwtcon_driver_get_wf_lut_pa() + 0x3C)
#define WF_LUT_L0_ADDR (hwtcon_driver_get_wf_lut_pa() + 0xF40)
#define WF_LUT_L0_PITCH (hwtcon_driver_get_wf_lut_pa() + 0x44)
#define WF_LUT_L1_CON (hwtcon_driver_get_wf_lut_pa() + 0x50)
#define WF_LUT_L1_SRC_SIZE (hwtcon_driver_get_wf_lut_pa() + 0x58)
#define WF_LUT_L1_OFFSET (hwtcon_driver_get_wf_lut_pa() + 0x5c)
#define WF_LUT_L1_ADDR (hwtcon_driver_get_wf_lut_pa() + 0xF60)
#define WF_LUT_L1_PITCH (hwtcon_driver_get_wf_lut_pa() + 0x64)
#define WF_LUT_L2_CON (hwtcon_driver_get_wf_lut_pa() + 0x70)
#define WF_LUT_L2_SRC_SIZE (hwtcon_driver_get_wf_lut_pa() + 0x78)
#define WF_LUT_L2_OFFSET (hwtcon_driver_get_wf_lut_pa() + 0x7c)
#define WF_LUT_L2_ADDR (hwtcon_driver_get_wf_lut_pa() + 0xF80)
#define WF_LUT_L2_PITCH (hwtcon_driver_get_wf_lut_pa() + 0x84)
#define WF_LUT_L3_CON (hwtcon_driver_get_wf_lut_pa() + 0x90)
#define WF_LUT_L3_SRC_SIZE (hwtcon_driver_get_wf_lut_pa() + 0x98)
#define WF_LUT_L3_OFFSET (hwtcon_driver_get_wf_lut_pa() + 0x9C)
#define WF_LUT_L3_ADDR (hwtcon_driver_get_wf_lut_pa() + 0xFA0)
#define WF_LUT_L3_PITCH (hwtcon_driver_get_wf_lut_pa() + 0xA4)
#define WF_LUT_RDMA0_CTRL (hwtcon_driver_get_wf_lut_pa() + 0xC0)
#define WF_LUT_RDMA0_MEM_GMC_SETTING1 (hwtcon_driver_get_wf_lut_pa() + 0xC8)
#define WF_LUT_RDMA0_MEM_SLOW_CON (hwtcon_driver_get_wf_lut_pa() + 0xCC)
#define WF_LUT_RDMA0_FIFO_CTRL (hwtcon_driver_get_wf_lut_pa() + 0xD0)
#define WF_LUT_RDMA1_CTRL (hwtcon_driver_get_wf_lut_pa() + 0xE0)
#define WF_LUT_RDMA1_MEM_GMC_SETTING1 (hwtcon_driver_get_wf_lut_pa() + 0xE8)
#define WF_LUT_RDMA1_MEM_SLOW_CON (hwtcon_driver_get_wf_lut_pa() + 0xEC)
#define WF_LUT_RDMA1_FIFO_CTRL (hwtcon_driver_get_wf_lut_pa() + 0xF0)
#define WF_LUT_RDMA2_CTRL (hwtcon_driver_get_wf_lut_pa() + 0x100)
#define WF_LUT_RDMA2_MEM_GMC_SETTING1 (hwtcon_driver_get_wf_lut_pa() + 0x108)
#define WF_LUT_RDMA2_MEM_SLOW_CON (hwtcon_driver_get_wf_lut_pa() + 0x10C)
#define WF_LUT_RDMA2_FIFO_CTRL (hwtcon_driver_get_wf_lut_pa() + 0x110)
#define WF_LUT_RDMA3_CTRL (hwtcon_driver_get_wf_lut_pa() + 0x120)
#define WF_LUT_RDMA3_MEM_GMC_SETTING1 (hwtcon_driver_get_wf_lut_pa() + 0x128)
#define WF_LUT_RDMA3_MEM_SLOW_CON (hwtcon_driver_get_wf_lut_pa() + 0x12C)
#define WF_LUT_RDMA3_FIFO_CTRL (hwtcon_driver_get_wf_lut_pa() + 0x130)
#define WF_LUT_DEBUG_MON_SEL (hwtcon_driver_get_wf_lut_pa() + 0x1D4)
#define WF_LUT_RDMA0_MEM_GMC_SETTING2 (hwtcon_driver_get_wf_lut_pa() + 0x1E0)
#define WF_LUT_RDMA1_MEM_GMC_SETTING2 (hwtcon_driver_get_wf_lut_pa() + 0x1E4)
#define WF_LUT_RDMA2_MEM_GMC_SETTING2 (hwtcon_driver_get_wf_lut_pa() + 0x1E8)
#define WF_LUT_RDMA3_MEM_GMC_SETTING2 (hwtcon_driver_get_wf_lut_pa() + 0x1EC)
#define WF_LUT_DUMMY_REG (hwtcon_driver_get_wf_lut_pa() + 0x200)
#define WF_LUT_FLOW_CTRL_DBG (hwtcon_driver_get_wf_lut_pa() + 0x240)
#define WF_LUT_ADDCON_DBG (hwtcon_driver_get_wf_lut_pa() + 0x244)
#define WF_LUT_RDMA0_DBG (hwtcon_driver_get_wf_lut_pa() + 0x24C)
#define WF_LUT_RDMA1_DBG (hwtcon_driver_get_wf_lut_pa() + 0x250)
#define WF_LUT_RDMA2_DBG (hwtcon_driver_get_wf_lut_pa() + 0x254)
#define WF_LUT_RDMA3_DBG (hwtcon_driver_get_wf_lut_pa() + 0x258)
#define WF_LUT_EN_STA0 (hwtcon_driver_get_wf_lut_pa() + 0x270)
#define WF_LUT_EN_STA1 (hwtcon_driver_get_wf_lut_pa() + 0x274)
#define WF_LUT_SECURE (hwtcon_driver_get_wf_lut_pa() + 0xFC0)
#define WF_LUT_GREQ_LAYER_CNT (hwtcon_driver_get_wf_lut_pa() + 0x234)
#define WF_LUT_SMI_DBG (hwtcon_driver_get_wf_lut_pa() + 0x230)
#define WF_LUT_DUAL_MODE (hwtcon_driver_get_wf_lut_pa() + 0xD00)
#define WF_LUT_EN_0 (hwtcon_driver_get_wf_lut_pa() + 0xD04)
#define WF_LUT_EN_1 (hwtcon_driver_get_wf_lut_pa() + 0xD08)
#define WF_LUT_CON (hwtcon_driver_get_wf_lut_pa() + 0xD0C)
#define WF_LUT_LEN_0 (hwtcon_driver_get_wf_lut_pa() + 0xD30)
#define WF_LUT_LEN_1 (hwtcon_driver_get_wf_lut_pa() + 0xD34)
#define WF_LUT_LEN_2 (hwtcon_driver_get_wf_lut_pa() + 0xD38)
#define WF_LUT_LEN_3 (hwtcon_driver_get_wf_lut_pa() + 0xD3C)
#define WF_LUT_LEN_4 (hwtcon_driver_get_wf_lut_pa() + 0xD40)
#define WF_LUT_LEN_5 (hwtcon_driver_get_wf_lut_pa() + 0xD44)
#define WF_LUT_LEN_6 (hwtcon_driver_get_wf_lut_pa() + 0xD48)
#define WF_LUT_LEN_7 (hwtcon_driver_get_wf_lut_pa() + 0xD4C)
#define WF_MODE_SEL_0 (hwtcon_driver_get_wf_lut_pa() + 0xD50)
#define WF_MODE_SEL_1 (hwtcon_driver_get_wf_lut_pa() + 0xD54)
#define WF_MODE_SEL_2 (hwtcon_driver_get_wf_lut_pa() + 0xD58)
#define WF_MODE_SEL_3 (hwtcon_driver_get_wf_lut_pa() + 0xD5C)
#define WF_MODE_SEL_4 (hwtcon_driver_get_wf_lut_pa() + 0xD60)
#define WF_MODE_SEL_5 (hwtcon_driver_get_wf_lut_pa() + 0xD64)
#define WF_MODE_SEL_6 (hwtcon_driver_get_wf_lut_pa() + 0xD68)
#define WF_MODE_SEL_7 (hwtcon_driver_get_wf_lut_pa() + 0xD6C)
#define WF_LUT_CHKSUM_0 (hwtcon_driver_get_wf_lut_pa() + 0xD70)
#define WF_LUT_CHKSUM_1 (hwtcon_driver_get_wf_lut_pa() + 0xD74)
#define WF_LUT_CHKSUM_2 (hwtcon_driver_get_wf_lut_pa() + 0xD78)
#define WF_LUT_CHKSUM_3 (hwtcon_driver_get_wf_lut_pa() + 0xD7C)
#define WF_LUT_CHKSUM_4 (hwtcon_driver_get_wf_lut_pa() + 0xD80)
#define WF_LUT_CHKSUM_0_VA (hwtcon_driver_get_wf_lut_va() + 0xD70)
#define WF_LUT_CHKSUM_1_VA (hwtcon_driver_get_wf_lut_va() + 0xD74)
#define WF_LUT_CHKSUM_2_VA (hwtcon_driver_get_wf_lut_va() + 0xD78)
#define WF_LUT_CHKSUM_3_VA (hwtcon_driver_get_wf_lut_va() + 0xD7C)
#define WF_LUT_CHKSUM_4_VA (hwtcon_driver_get_wf_lut_va() + 0xD80)
#define WF_LUT_LINK_MODE (hwtcon_driver_get_wf_lut_pa() + 0xD84)
#define WF_LUT_TIMEOUT_CFG (hwtcon_driver_get_wf_lut_pa() + 0xD88)
#define WF_LUT_DEBUG_SRAM (hwtcon_driver_get_wf_lut_pa() + 0xD8C)
#define WF_LUT_MERGE0_START (hwtcon_driver_get_wf_lut_pa() + 0xD90)
#define WF_LUT_MERGE0_SIZE (hwtcon_driver_get_wf_lut_pa() + 0xD94)
#define WF_LUT_MERGE1_START (hwtcon_driver_get_wf_lut_pa() + 0xD98)
#define WF_LUT_MERGE1_SIZE (hwtcon_driver_get_wf_lut_pa() + 0xD9C)
#define WF_LUT_MERGE2_START (hwtcon_driver_get_wf_lut_pa() + 0xDA0)
#define WF_LUT_MERGE2_SIZE (hwtcon_driver_get_wf_lut_pa() + 0xDA4)
#define WF_LUT_MERGE3_START (hwtcon_driver_get_wf_lut_pa() + 0xDA8)
#define WF_LUT_MERGE3_SIZE (hwtcon_driver_get_wf_lut_pa() + 0xDAC)
#define WF_LUT_MERGE_POS_0 (hwtcon_driver_get_wf_lut_pa() + 0xDB0)
#define WF_LUT_MERGE_POS_1 (hwtcon_driver_get_wf_lut_pa() + 0xDB4)
#define WF_LUT_INFO_XY_CFG (hwtcon_driver_get_wf_lut_pa() + 0xDB8)
#define WF_LUT_INFO_WH_CFG (hwtcon_driver_get_wf_lut_pa() + 0xDBC)
#define WF_LUT_LINK_BASE_ADDR (hwtcon_driver_get_wf_lut_pa() + 0xF00)
#define WF_LUT_LINK_BASE_ADDR_1 (hwtcon_driver_get_wf_lut_pa() + 0xF04)
#define WF_LUT_MOUT (hwtcon_driver_get_wf_lut_pa() + 0xF08)
#define WF_LUT_ADDR_0 (hwtcon_driver_get_wf_lut_pa() + 0xF10)
#define WF_LUT_ADDR_1 (hwtcon_driver_get_wf_lut_pa() + 0xF14)
#define WF_LUT_ADDR_2 (hwtcon_driver_get_wf_lut_pa() + 0xF18)
#define WF_LUT_ADDR_3 (hwtcon_driver_get_wf_lut_pa() + 0xF1C)
#define WF_LUT_ADDR_4 (hwtcon_driver_get_wf_lut_pa() + 0xF20)
#define WF_LUT_ADDR_5 (hwtcon_driver_get_wf_lut_pa() + 0xF24)
#define WF_LUT_ADDR_6 (hwtcon_driver_get_wf_lut_pa() + 0xF28)
#define WF_LUT_ADDR_7 (hwtcon_driver_get_wf_lut_pa() + 0xF2C)

#define WF_LUT_RDMA0_DBG_VA (hwtcon_driver_get_wf_lut_va() + 0x24C)
#define WF_LUT_RDMA1_DBG_VA (hwtcon_driver_get_wf_lut_va() + 0x250)
#define WF_LUT_ADDR_0_VA	(hwtcon_driver_get_wf_lut_va() + 0xF10)
#define WF_LUT_ADDR_1_VA	(hwtcon_driver_get_wf_lut_va() + 0xF14)
#define WF_LUT_ADDR_2_VA	(hwtcon_driver_get_wf_lut_va() + 0xF18)
#define WF_LUT_ADDR_3_VA	(hwtcon_driver_get_wf_lut_va() + 0xF1C)
#define WF_LUT_ADDR_4_VA	(hwtcon_driver_get_wf_lut_va() + 0xF20)
#define WF_LUT_ADDR_5_VA	(hwtcon_driver_get_wf_lut_va() + 0xF24)
#define WF_LUT_ADDR_6_VA	(hwtcon_driver_get_wf_lut_va() + 0xF28)
#define WF_LUT_ADDR_7_VA	(hwtcon_driver_get_wf_lut_va() + 0xF2C)

#endif /* __HWTCON_REG_H__ */
