name: Download Kindle Source
on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download and extract
        run: |
          wget -q "https://s3.amazonaws.com/kindledownloads/Kindle_src_5.18.2_4434540025.tar.gz"
          tar xzf Kindle_src_5.18.2_4434540025.tar.gz
          rm Kindle_src_5.18.2_4434540025.tar.gz
      - name: Commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Kindle GPL source"
          git push
