name: Download Kindle Source
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract
        run: |
          wget -q "https://s3.amazonaws.com/kindledownloads/Kindle_src_5.19.2_4670760040.tar.gz"
          tar xzf Kindle_src_5.19.2_4670760040.tar.gz
          rm Kindle_src_5.19.2_4670760040.tar.gz
          cd gplrelease
          tar xzf linux-4.9.tar.gz
          rm linux-4.9.tar.gz
          tar xzf uboot.tar.gz
          rm uboot.tar.gz

      - name: Commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Kindle GPL source extracted"
          git push
